"""auto sync is_catalog from fifo stock, remove global catalog concept

Revision ID: 1c84a872bb77
Revises: bb740ad8689b
Create Date: 2026-05-04 12:21:54.089677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c84a872bb77'
down_revision: Union[str, None] = 'bb740ad8689b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Usa IF EXISTS para tolerar bancos que não têm esses índices (ex: produção Neon)
    op.execute("DROP INDEX IF EXISTS ix_refresh_tokens_last_used_at")
    op.execute("DROP INDEX IF EXISTS ix_refresh_tokens_token_hash")
    op.execute("DROP INDEX IF EXISTS ix_refresh_tokens_user_id")

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'refresh_tokens' in inspector.get_table_names():
        op.drop_table('refresh_tokens')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('last_used_at', sa.DATETIME(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('revoked', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('ix_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('ix_refresh_tokens_last_used_at', 'refresh_tokens', ['last_used_at'], unique=False)
    # ### end Alembic commands ###
