"""add_product_tags

Revision ID: 7789d0400d1f
Revises: d08d16b3c7ca
Create Date: 2026-03-11 16:01:13.746673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7789d0400d1f'
down_revision: Union[str, None] = 'd08d16b3c7ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_tags',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tag_type', sa.String(length=30), nullable=False),
    sa.Column('tag_value', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('tenant_id', sa.Integer(), nullable=True, comment='Tenant/Store identifier'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['stores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_tags_id'), 'product_tags', ['id'], unique=False)
    op.create_index(op.f('ix_product_tags_product_id'), 'product_tags', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_tags_tag_type'), 'product_tags', ['tag_type'], unique=False)
    op.create_index(op.f('ix_product_tags_tag_value'), 'product_tags', ['tag_value'], unique=False)
    op.create_index(op.f('ix_product_tags_tenant_id'), 'product_tags', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_tags_tenant_id'), table_name='product_tags')
    op.drop_index(op.f('ix_product_tags_tag_value'), table_name='product_tags')
    op.drop_index(op.f('ix_product_tags_tag_type'), table_name='product_tags')
    op.drop_index(op.f('ix_product_tags_product_id'), table_name='product_tags')
    op.drop_index(op.f('ix_product_tags_id'), table_name='product_tags')
    op.drop_table('product_tags')
    # ### end Alembic commands ###
