"""add lookbook looks wishlist

Revision ID: d08d16b3c7ca
Revises: ea3615df1b12
Create Date: 2026-03-11 15:48:59.230547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd08d16b3c7ca'
down_revision: Union[str, None] = 'ea3615df1b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('looks',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('discount_percentage', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('tenant_id', sa.Integer(), nullable=True, comment='Tenant/Store identifier'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['stores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_looks_customer_id'), 'looks', ['customer_id'], unique=False)
    op.create_index(op.f('ix_looks_id'), 'looks', ['id'], unique=False)
    op.create_index(op.f('ix_looks_tenant_id'), 'looks', ['tenant_id'], unique=False)
    op.create_table('look_items',
    sa.Column('look_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('tenant_id', sa.Integer(), nullable=True, comment='Tenant/Store identifier'),
    sa.ForeignKeyConstraint(['look_id'], ['looks.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['stores.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_look_items_id'), 'look_items', ['id'], unique=False)
    op.create_index(op.f('ix_look_items_look_id'), 'look_items', ['look_id'], unique=False)
    op.create_index(op.f('ix_look_items_product_id'), 'look_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_look_items_tenant_id'), 'look_items', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_look_items_variant_id'), 'look_items', ['variant_id'], unique=False)
    op.create_table('wishlists',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('look_id', sa.Integer(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Record last update timestamp'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('tenant_id', sa.Integer(), nullable=True, comment='Tenant/Store identifier'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['look_id'], ['looks.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['stores.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wishlists_customer_id'), 'wishlists', ['customer_id'], unique=False)
    op.create_index(op.f('ix_wishlists_id'), 'wishlists', ['id'], unique=False)
    op.create_index(op.f('ix_wishlists_look_id'), 'wishlists', ['look_id'], unique=False)
    op.create_index(op.f('ix_wishlists_product_id'), 'wishlists', ['product_id'], unique=False)
    op.create_index(op.f('ix_wishlists_tenant_id'), 'wishlists', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_wishlists_variant_id'), 'wishlists', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('token', sa.VARCHAR(), nullable=False),
    sa.Column('blacklisted_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index('ix_token_blacklist_token', 'token_blacklist', ['token'], unique=False)
    op.drop_index(op.f('ix_wishlists_variant_id'), table_name='wishlists')
    op.drop_index(op.f('ix_wishlists_tenant_id'), table_name='wishlists')
    op.drop_index(op.f('ix_wishlists_product_id'), table_name='wishlists')
    op.drop_index(op.f('ix_wishlists_look_id'), table_name='wishlists')
    op.drop_index(op.f('ix_wishlists_id'), table_name='wishlists')
    op.drop_index(op.f('ix_wishlists_customer_id'), table_name='wishlists')
    op.drop_table('wishlists')
    op.drop_index(op.f('ix_look_items_variant_id'), table_name='look_items')
    op.drop_index(op.f('ix_look_items_tenant_id'), table_name='look_items')
    op.drop_index(op.f('ix_look_items_product_id'), table_name='look_items')
    op.drop_index(op.f('ix_look_items_look_id'), table_name='look_items')
    op.drop_index(op.f('ix_look_items_id'), table_name='look_items')
    op.drop_table('look_items')
    op.drop_index(op.f('ix_looks_tenant_id'), table_name='looks')
    op.drop_index(op.f('ix_looks_id'), table_name='looks')
    op.drop_index(op.f('ix_looks_customer_id'), table_name='looks')
    op.drop_table('looks')
    # ### end Alembic commands ###
