"""add pix_key and pix_key_type to store

Revision ID: eb4d9bbde072
Revises: f9b57a51b0f0
Create Date: 2026-05-05 07:51:01.396361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb4d9bbde072'
down_revision: Union[str, None] = 'f9b57a51b0f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refresh_tokens_last_used_at', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.add_column('stores', sa.Column('pix_key', sa.String(length=255), nullable=True, comment='Chave PIX do lojista (CPF, CNPJ, email, telefone ou chave aleatória)'))
    op.add_column('stores', sa.Column('pix_key_type', sa.String(length=20), nullable=True, comment='Tipo da chave PIX: cpf, cnpj, email, phone, random'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'pix_key_type')
    op.drop_column('stores', 'pix_key')
    op.create_table('refresh_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('last_used_at', sa.DATETIME(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('revoked', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('ix_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('ix_refresh_tokens_last_used_at', 'refresh_tokens', ['last_used_at'], unique=False)
    # ### end Alembic commands ###
