name: Mobile Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'mobile/**'
      - '.github/workflows/mobile-tests.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'mobile/**'

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: mobile/package-lock.json
    
    - name: Install dependencies
      working-directory: ./mobile
      run: npm ci
    
    - name: Run ESLint
      working-directory: ./mobile
      run: npm run lint || true
    
    - name: TypeScript type check
      working-directory: ./mobile
      run: npx tsc --noEmit
    
    - name: Check code formatting with Prettier
      working-directory: ./mobile
      run: npx prettier --check . || true

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: mobile/package-lock.json
    
    - name: Install dependencies
      working-directory: ./mobile
      run: npm ci
    
    - name: Run tests
      working-directory: ./mobile
      run: npm test || echo "No tests configured yet"
    
    - name: Generate test coverage
      working-directory: ./mobile
      run: npm run test:coverage || true

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: mobile/package-lock.json
    
    - name: Setup Expo
      uses: expo/expo-github-action@v8
      with:
        expo-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
    
    - name: Install dependencies
      working-directory: ./mobile
      run: npm ci
    
    - name: Build Android APK (Development)
      working-directory: ./mobile
      run: |
        # This would build the app in a real scenario
        # npx eas-cli build --platform android --profile development --non-interactive
        echo "Build step - would build Android APK"
    
    - name: Build iOS App (Development)
      working-directory: ./mobile
      run: |
        # This would build the app in a real scenario
        # npx eas-cli build --platform ios --profile development --non-interactive
        echo "Build step - would build iOS app"

  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: mobile/package-lock.json
    
    - name: Install dependencies
      working-directory: ./mobile
      run: npm ci
    
    - name: Analyze bundle size
      working-directory: ./mobile
      run: |
        npx expo export --dump-sourcemap || true
    
    - name: Check for security vulnerabilities
      working-directory: ./mobile
      run: |
        npm audit --audit-level=moderate || true
